const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const session = fs.readFileSync('public/dashboard-session.js','utf8');
const context = {};
vm.createContext(context);
vm.runInContext(session.slice(session.indexOf('function callbackInstructionFromText('),session.indexOf('function nextStepForCall(')),context);
assert.equal(context.callbackInstructionFromText('Rückruf morgen ab 14 Uhr gewünscht.'),'Rückruf: morgen ab 14 Uhr');
assert.equal(context.callbackInstructionFromText('Der Termin ist um 10 Uhr. Rückruf gewünscht.'),'','appointment time must not become callback time');
assert.equal(context.callbackInstructionFromText('Herr Weber ist ab 14 Uhr erreichbar.'),'Rückruf: ab 14 Uhr');
assert.equal(context.callbackInstructionFromText('Rückruf am Freitag um 09:30 Uhr.'),'Rückruf: am Freitag um 09:30 Uhr');
console.log('Callback time extraction passed');
const sessionStart = session.indexOf('function extractFieldByLabels(');
vm.runInContext(session.slice(sessionStart,session.indexOf('function callbackInstructionFromText(')),context);
vm.runInContext(session.slice(session.indexOf('function normalizeSummary('),session.indexOf('function cleanFactText(')),context);
context.detailSummarySource = c => c.summary || '';
context.classifyCall = () => ({key:'callback',next:'Zurückrufen'});
context.nextStepForCall = () => 'Zurückrufen';
vm.runInContext(fs.readFileSync('public/dashboard-work.js','utf8'),context);
const brief = context.callBrief({summary:'Rückruf gewünscht: Die Heizung bleibt kalt. Herr Weber ist ab 14 Uhr erreichbar.'});
assert.equal(brief.title,'Die Heizung bleibt kalt');
assert.equal(brief.facts.length,1,'do not repeat the headline in bullets');
assert.equal(brief.time,'Rückruf: ab 14 Uhr');
assert.equal(context.callBrief({summary:''}).title,'Anliegen noch nicht verfügbar');
console.log('Scannable call briefs passed');
